timeout: 1800s
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/demoweb:$TAG_NAME', '.']
  id: 'build-gcr'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/demoweb:$TAG_NAME']
  id: 'push-gcr'
- name: 'peihsinsu/g8'
  args: ['g8','deploy','app.yaml','--dry']
  id: 'g8'
- name: 'peihsinsu/g8'
  args: ['ls']
  id: 'ls-pwd'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ["apply","-f","g8/deployment.yaml"]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-184'
  waitFor:
  - 'g8'
